(load "gfx_utils.scm")
(load "game_lib.scm")

(define box-model (quick-load-model "test/box.obj"))
(define test-guy-model (quick-load-model "test/Thriller Part 4.dae"))
(define test-guy-animator (animator-create))
(define test-guy-animation (animation-create "test/Thriller Part 4.dae" test-guy-model))
(define box-transform (make-transform))
(define box-texture (quick-load-texture "pink_checkerboard.png"))
(define homer-texture (quick-load-texture "test/homer.png"))
(set! (transform-sx box-transform) 64.0)
(set! (transform-sy box-transform) 1.0)
(set! (transform-sz box-transform) 64.0)
(set! (transform-rz box-transform) 1.0)
(set! (transform-rw box-transform) 0.0)
(update-transform box-transform)

(define box2-transform (make-transform))
(set! (transform-pz box2-transform) -5.0)
(set! (transform-sx box2-transform) 300.0)
(set! (transform-sy box2-transform) 300.0)
(set! (transform-sz box2-transform) 300.0)
(set! (transform-rz box2-transform) 1.0)
(set! (transform-rw box2-transform) 0.0)
(update-transform box2-transform)

(define sphere-transform (make-transform))
(set! (transform-sx sphere-transform) 5.0)
(set! (transform-sy sphere-transform) 5.0)
(set! (transform-sz sphere-transform) 5.0)
(set! (transform-rz sphere-transform) 1.0)
(set! (transform-rw sphere-transform) 0.0)
(update-transform sphere-transform)

;(define test-light (light-create))
;(light-set-clq test-light 1.0 0.007 0.0002)
;(light-set-ambient test-light 0.8 1.0 0.8)
;(light-set-diffuse test-light 0.2 1.0 0.3)
;(light-set-specular test-light 0.0 1.0 0.1)
;(light-set-position test-light -15.0 15.0 15.0)

(animator-set-animation test-guy-animator test-guy-animation)

(define (script-frame world camera) (gfxutils-frame world camera) (gamelib-frame world camera)
    (if (input-get-focus) (gamelib-debug-3d-controller camera))
    (set! (transform-pz sphere-transform) (* (cos (world-time)) 4))
    (set! (transform-pz sphere-transform) (* (cos (world-time)) 4))
    (set! (transform-px sphere-transform) (* (sin (world-time)) 4))
    (update-transform sphere-transform)
    (animator-update test-guy-animator (world-delta-time world)))

(define (script-frame-render world light-pass)
    (lightarea-use camera-light-area world)
    (gl-bind-texture 0 box-texture)
    (world-draw-object world normal-shader box-model box-transform)
    (world-draw-object world normal-shader sky-ball sphere-transform)
    (gfxutils-set-animator light-pass test-guy-animator rigged-shader world)
    (gl-bind-texture 0 homer-texture)
    (world-draw-object world rigged-shader test-guy-model box2-transform))

(define (script-frame-ui world)
    (let ((ui-data (world-get-ui world))) (ui-draw-text ui-data 0 0 "Hullo World"))
    (let ((ui-data (world-get-ui world))) (ui-draw-text ui-data 0 16 (format #f "animator-current-time: ~A" (animator-current-time test-guy-animator)))))